study/DJANGO/task/APR17/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('create/', views.create, name='create'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/likes/', views.likes, name='likes'),
    path('<int:pk>/comments/', views.comment_create, name='comment_create'),
    path('<int:pk>/comments/<int:comment_pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<int:pk>/comments/<int:comment_pk>/likes/', views.comment_likes, name='comment_likes'),
]

study/DJANGO/task/APR17/articles/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import ArticleForm,CommentForm
from .models import Article,Comment, Emote


# Create your views here.
def index(request):
    context = {
        'articles': Article.objects.order_by('-pk'),
    }
    return render(request, 'index.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            article.user = request.user
            article.save()
            return redirect('articles:detail', article.pk)
    else:
        form = ArticleForm()
    context = {
        'form' : form
    }
    return render(request, 'create.html', context)



@login_required
def detail(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm()
    comments = article.comment_set.all()
    context = {
        'article': article,
        'comment_form' : comment_form,
        'comments' : comments,
        'like': article.count_likes_user(),
    }
    return render(request, 'detail.html', context)

@login_required
def delete(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        article.delete()
    return redirect('articles:index')

@login_required
def edit(request, pk):
    article = Article.objects.get(pk=pk)
    if request.user == article.user:
        if request.method == 'POST':
            form = ArticleForm(request.POST, request.FILES, instance=article)
            if form.is_valid():
                article = form.save()
                return redirect('articles:detail', article.pk)
        else:
            form = ArticleForm(instance=article)
    else:
        return redirect('articles:detail', article.pk)
    context = {
        'article': article,
        'form' : form,
    }
    return render(request, 'edit.html', context)

def likes(request, pk):
    article = Article.objects.get(pk=pk)
    if article.like_users.filter(pk=request.user.pk).exists():
        article.like_users.remove(request.user)
    else:
        article.like_users.add(request.user)
    return redirect('articles:detail', article.pk)

@login_required
def comment_create(request, pk):
    article = Article.objects.get(pk=pk)
    comment_form = CommentForm(request.POST)
    comments = article.comment_set.all()
    if comment_form.is_valid():
        comment = comment_form.save(commit=False)
        comment.article = article
        comment.user = request.user
        comment.save()
        return redirect('articles:detail', article.pk)
    context = {
        'article' : article,
        'comment_form' : comment_form,
        'comments' : comments,
        'like': article.count_likes_user(),
        'comment_like': comment.count_likes_comment(),
    }
    return render(request, 'detail.html', context)

@login_required
def comment_delete(request, pk, comment_pk):
    comment = Comment.objects.get(pk=comment_pk)
    if request.user == comment.user:
        comment.delete()
    return redirect('articles:detail', pk)


def comment_likes(request, pk, comment_pk):
    article = Article.objects.get(pk=pk)
    comment = Comment.objects.get(pk=comment_pk)
    if comment.like_users.filter(pk=request.user.pk).exists():
        comment.like_users.remove(request.user)
    else:
        comment.like_users.add(request.user)
    return redirect('articles:detail', article.pk)

study/DJANGO/task/APR17/articles/templates/detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %} {{ article.title }} {% endblock title %}
{% block content %}
<div class="content">
    <p class="review_head">{{ article.title }}</p>
    <div class="detail_box">
        <div class="detail_btn_box">
            {% if article.user == request.user %}
            <a href="{% url 'articles:delete' article.pk %}" class="btn comment_btn_style" onclick="return confirm('삭제하시겠습니까?')">Delete</a>
            <a href="{% url 'articles:edit' article.pk %}" class="btn comment_btn_style" >Edit</a>
            {% endif %}
            <a href="{% url 'articles:index'%}" class="btn comment_btn_style" >Home</a>
        </div>
        <p class="text_box article_txt">작성 일자: {{ article.created_at|date:'Y-m-d' }}</p>
        <p class="text_box article_txt">작성자: {{ article.user }}</p>
        <form action="{% url 'articles:likes' article.pk %}" method='POST'>
        {% csrf_token %}
        {% if user in article.like_users.all %}
            <button class="btn btn-link text-danger  pe-1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
            </svg>
            </button>
        {% else %}
            <button class="btn btn-link text-danger  pe-1">
            <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
                <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
            </svg>
            </button>
        {% endif %}
        {{ like }}
        </form>     
    </div>
    <div class="article_body">
        {% if article.img_file %}
        <img src="{{ article.img_file.url }}" alt="사진" class="img">
        {% else %}
        <img src="{% static 'img/img_none.jpg' %}" alt="사진없음" class="img">
        {% endif %}
        <p>{{ article.content }}</p>
    </div>
</div>
<div class="comment_box">
    <h2>댓글 ({{ article.comment_set.all|length }})</h2>
    <div class = "comment_input">
        <form action="{% url 'articles:comment_create' article.pk %}" method="POST" class="row g-3">
        {% csrf_token %}
        <div class="col-10">
            {{ comment_form }}
        </div>
        <div class="col-2">
            <input type="submit" class="btn comment_btn_style" value="등록">
        </div>
        </form>
    </div>
    <div>
        <ul>
        {% for comment in comments  %}
            <li>
                <div class="input-group">
                <p class="text_box comment_txt">{{ comment.user }}: {{ comment.content }}</p>
                {% if comment.user == request.user %}
                <form action="{% url 'articles:comment_delete' article.pk comment.pk %}" method="POST">
                    {% csrf_token %}
                    <input type="submit" value="삭제" class="btn comment_btn_style" onclick="return confirm('삭제하시겠습니까?')"> 
                </form>
                {% endif %}
                </div>
                <div class="input-group">
                <p class="text_box article_txt"> {{ comment.created_string }}</p>
                <form action="{% url 'articles:comment_likes' article.pk comment.pk%}" method='POST'>
                    {% csrf_token %}
                    {% if user in comment.like_users.all %}
                        <button class="btn btn-link text-danger pe-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
                            <path d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
                        </svg>
                        </button>
                    {% else %}
                        <button class="btn btn-link text-danger  pe-1">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart" viewBox="0 0 16 16">
                            <path d="m8 6.236-.894-1.789c-.222-.443-.607-1.08-1.152-1.595C5.418 2.345 4.776 2 4 2 2.324 2 1 3.326 1 4.92c0 1.211.554 2.066 1.868 3.37.337.334.721.695 1.146 1.093C5.122 10.423 6.5 11.717 8 13.447c1.5-1.73 2.878-3.024 3.986-4.064.425-.398.81-.76 1.146-1.093C14.446 6.986 15 6.131 15 4.92 15 3.326 13.676 2 12 2c-.777 0-1.418.345-1.954.852-.545.515-.93 1.152-1.152 1.595L8 6.236zm.392 8.292a.513.513 0 0 1-.784 0c-1.601-1.902-3.05-3.262-4.243-4.381C1.3 8.208 0 6.989 0 4.92 0 2.755 1.79 1 4 1c1.6 0 2.719 1.05 3.404 2.008.26.365.458.716.596.992a7.55 7.55 0 0 1 .596-.992C9.281 2.049 10.4 1 12 1c2.21 0 4 1.755 4 3.92 0 2.069-1.3 3.288-3.365 5.227-1.193 1.12-2.642 2.48-4.243 4.38z"/>
                        </svg>
                        </button>
                    {% endif %}
                    {{ comment.count_likes_comment }}
                </form>
                </div>  
            </li>
        {% empty %}
        <div>
            <p class="text_box comment_txt">첫번째 댓글을 남겨주세요.</p>
        </div>
        {% endfor %}
        </ul>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR17/articles/templates/index.html
{% extends 'base.html' %}
{% block title %}Home{% endblock title %}
{% load static %}
{% block content %}

<div class="index-title-box">
  <p class="index-title"><svg width="35px" height="35px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M10.063 21.7917C10.3894 22.1483 11 21.9534 11 21.4699V4C10 3 8.91255 2.57151 7.78361 2.32246C5.78311 1.88113 4.0024 1.97693 2.91265 2.11876C1.70543 2.27587 1 3.34931 1 4.40561V17.5662C1 18.9895 2.18834 20.1115 3.56807 20.066C4.71011 20.0284 6.2952 20.0688 7.73105 20.4158C8.82596 20.6803 9.52237 21.2009 10.063 21.7917Z" fill="#1A6ED8"></path> <path d="M13.937 21.7917C13.6106 22.1483 13 21.9534 13 21.4699V4C14 3 15.0874 2.57151 16.2164 2.32246C18.2169 1.88113 19.9976 1.97693 21.0873 2.11876C22.2946 2.27587 23 3.34931 23 4.40561V17.5662C23 18.9895 21.8117 20.1115 20.4319 20.066C19.2899 20.0284 17.7048 20.0688 16.269 20.4158C15.174 20.6803 14.4776 21.2009 13.937 21.7917Z" fill="#1A6ED8"></path> </g></svg>  스토리</p>
</div>
<div class="index_content">
    {% for article in articles %}
    <div class="card">
      <a href="{% url 'articles:detail' article.pk %}" class="title">
        <div>
          {% if article.img_file %}
            <img src="{{ article.img_file.url }}" alt="사진" class="card-image">
          {% else %}
            <img src="{% static 'img/img_none.jpg' %}" alt="사진없음" class="card-image">
          {% endif %}
        </div>
        <div class="card-txt">
          <p class="text_box">{{ article.title }}({{ article.comment_set.all|length }})</p>
          <p class="article_txt">작성자: {{ article.user }} / 작성일: {{ article.created_string }}</p>
        </div>
      </a>
    </div>
    {% endfor %}
    {% comment %} <iframe width="560" height="315" src="https://www.youtube.com/embed/videoseries?list=PLB7PYmHaa-5ppOQ-7LyVYhyNyUhQtN12q&autoplay=1&mute=1" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe> {% endcomment %}
</div>


{% endblock content %}