study/DJANGO/task/MAR30/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include
from todos import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main),
    path('todos/',include('todos.urls')),
]

study/DJANGO/task/MAR30/todos/urls.py
from django.urls import path
from . import views

app_name='todos'
urlpatterns = [
    path('', views.todo, name = 'todo'),
    path('<int:pk>/', views.todocontent, name = 'todocontent'),
    path('create/', views.create, name = 'create'),
    path('success/', views.success, name = 'success'),
    path('<int:pk>/remove', views.remove, name = 'remove'),
    path('<int:pk>/edit', views.edit, name = 'edit'),
    path('<int:pk>/update', views.update, name = 'update'),
]

study/DJANGO/task/MAR30/todos/models.py
from django.db import models

# Create your models here.

class Todo(models.Model):
    title = models.CharField(max_length=80)
    content = models.TextField(null=True)
    completed = models.BooleanField(default=False)
    priority = models.IntegerField(default=3)
    created_at = models.DateField(auto_now_add=True)
    deadline = models.DateField(null=True)

study/DJANGO/task/MAR30/todos/views.py
from django.shortcuts import render, redirect
from .models import Todo

# Create your views here.

def main(request):
    return render(request, 'todos/main.html')

def todo(request):
    todos = Todo.objects.order_by('deadline')

    context = {
        'todos' : todos,
    }
    return render(request, 'todos/todos.html', context)

def todocontent(request, pk):
    todo = Todo.objects.get(pk=pk)
    context = {
        'todo' : todo,
    }
    return render(request, 'todos/todocontent.html', context)

def create(request):
    return render(request, 'todos/create.html')

def success(request):

    title = request.POST['title']
    content = request.POST['content']
    completed = request.POST.get('completed', False) == 'on'
    priority = request.POST['priority']
    deadline = request.POST['deadline']

    todo = Todo(title = title, content = content, completed = completed, priority = priority, deadline = deadline)
    todo.save()
    
    return redirect("todos:todocontent", todo.pk)

def remove(request, pk):
    todo = Todo.objects.get(pk=pk)
    todo.delete()
    return redirect("todos:todo")


def edit(request, pk):
    todo = Todo.objects.get(pk=pk)
    context = {
        'todo' : todo,
    }

    return render(request, 'todos/edit.html', context) 

def update(request, pk):
    todo = Todo.objects.get(pk=pk)

    todo.title = request.POST['title']
    todo.content = request.POST['content']
    todo.completed = request.POST.get('completed', False) == 'on'
    todo.priority = request.POST['priority']
    todo.deadline = request.POST['deadline']

    todo.save()
    
    return redirect("todos:todocontent", todo.pk)

study/DJANGO/task/MAR30/todos/templates/todos/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}
    
</head>
<body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
    crossorigin="anonymous"></script>
</body>
</html>

study/DJANGO/task/MAR30/todos/templates/todos/create.html
{% extends 'todos/base.html' %}

{% block style %}
<style>
@font-face {
    font-family: 'KCC-Ganpan';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/KCC-Ganpan.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
* {
    font-family: 'KCC-Ganpan';
}

a {
    text-decoration-line: none;
    color: pink;
    font-size: 20px;
}
</style>

{% endblock style %}


{% block content %}
<div class="container m-5 text-center">
  <h1>Todo 추가</h1>
  <div class="mx-auto text-start w-50">
    <form action="{% url 'todos:success' %}" method="POST">
        {% csrf_token %}
        <div class= "mb-3">
            <label for="title">Todo</label>
            <input type="text" class="form-control" name="title" id='title'>
        </div>
        <div class= "mb-3">
            <label for="content">Explanation</label>
            <textarea name="content" class="form-control" id="content" cols="30" rows="5"></textarea>
        </div>
        <div class= "mb-3">
            <label for="priority">Importance</label>
            <input type="Number" class="form-control" name="priority" id='priority' min = "0" value="3">
        </div>
        <div class= "mb-3">
            <label for="completed">completed</label>
            <input type="checkbox" name="completed" id='completed'>
        </div>
        <div class= "mb-3">
            <label for="deadline">Deadline</label>
            <input type="date" class="form-control" name="deadline" id='deadline' onchange="validateDeadline()" required>
        </div>
        <div style="display: flex;justify-content: center;align-items: center;">
        <input class="btn" style="color:pink; font-size:30px;" type="submit" id='submit-button' value="Save">
        <a href="{% url 'todos:todo' %}" style="font-size:30px;">Back</a>
        </div>
    </form>
  </div>
</div>

<script>
    function validateDeadline() {
        const deadlineInput = document.getElementsByName('deadline')[0];
        const submitButton = document.getElementById('submit-button');
    
        // deadline 값이 유효하지 않으면
        if (!Date.parse(deadlineInput.value)) {
            submitButton.disabled = true; // 저장 버튼 비활성화
        } else {
            submitButton.disabled = false; // 저장 버튼 활성화
        }
    }
</script>
{% endblock content %}

study/DJANGO/task/MAR30/todos/templates/todos/edit.html
{% extends 'todos/base.html' %}

{% block style %}
<style>
@font-face {
    font-family: 'KCC-Ganpan';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/KCC-Ganpan.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
* {
    font-family: 'KCC-Ganpan';
}

a {
    text-decoration-line: none;
    color: pink;
    font-size: 20px;
}
</style>

{% endblock style %}


{% block content %}
<div class="container m-5 text-center">
  <h1>Todo 수정</h1>
  <div class="mx-auto text-start w-50">
    <form action="{% url 'todos:update' todo.pk %}" method="POST">
        {% csrf_token %}
        <div class= "mb-3">
            <label for="title">Todo</label>
            <input type="text" class="form-control" name="title" id='title' value="{{ todo.title }}">
        </div>
        <div class= "mb-3">
            <label for="content">Explanation</label>
            <textarea name="content" class="form-control" id="content" cols="30" rows="5">{{ todo.content }}</textarea>
        </div>
        <div class= "mb-3">
            <label for="priority">Importance</label>
            <input type="Number" class="form-control" name="priority" id='priority' min = "0" value="{{ todo.priority }}">
        </div>
        <div class= "mb-3">
            <label for="completed">completed</label>
            <input type="checkbox" name="completed" id='completed' {% if todo.completed %}checked{% endif %}>
        </div>
        <div class= "mb-3">
            <label for="deadline">Deadline</label>
            <input type="date" class="form-control" name="deadline" id='deadline' value="{{ todo.deadline|date:'Y-m-d' }}" required>
        </div>
        <div style="display: flex;justify-content: center;align-items: center;">
        <input class="btn" style="color:pink; font-size:30px;" type="submit" value="Save">
        <a href="{% url 'todos:todocontent' todo.pk %}" style="font-size:30px;">Back</a>
        </div>
    </form>
  </div>
</div>
{% endblock content %}

study/DJANGO/task/MAR30/todos/templates/todos/main.html
{% extends 'todos/base.html' %}

{% block style %}
<style>
@font-face {
    font-family: 'KCC-Ganpan';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/KCC-Ganpan.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
* {
    font-family: 'KCC-Ganpan';
}

a {
    text-decoration-line: none;
    color: gray;
    font-size: 20px;
}
</style>

{% endblock style %}

{% block content %}
<div class="container m-5 text-center">
  <h1>Menu</h1>
  <a href="/todos/">Todo List</a><br>
</div>
{% endblock content %}

study/DJANGO/task/MAR30/todos/templates/todos/todocontent.html
{% extends 'todos/base.html' %}


{% block style %}
<style>
@font-face {
    font-family: 'KCC-Ganpan';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/KCC-Ganpan.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
* {
    font-family: 'KCC-Ganpan';
}

a {
    text-decoration-line: none;
    color: pink;
    font-size: 20px;
}

</style>

{% endblock style %}

{% block content %}
<div class="container m-5 p-2">
    <div class="text-start ms-5">
    <h1>Todo</h1>
    <p>Number: {{ todo.pk }}</p>
    <p>Todo: {{ todo.title }}</p>
    <p>Explanation: {{ todo.content }}</p>

    <label for="completed" class= "mb-3">completed</label>
    <input type="checkbox" name="completed" id="completed" 
    style='zoom:1.5;' {% if todo.completed %}checked{% endif %} disabled>

    <p>Importance: {{ todo.priority }}</p>
    <p>Created: {{ todo.created_at }}</p>
    <p>Deadline: {{ todo.deadline }}</p>
    <a href="{% url 'todos:edit' todo.pk %}" class = "me-2">Edit</a>
    <a href="{% url 'todos:remove' todo.pk %}" class = "me-2" onclick="return confirm('정말 삭제하시겠습니까?')">Delete</a>
    <a href="{% url 'todos:todo' %}">Back</a>
   </div>
</div>

{% endblock content %}

study/DJANGO/task/MAR30/todos/templates/todos/todos.html
{% extends 'todos/base.html' %}


{% block style %}
<style>
@font-face {
    font-family: 'KCC-Ganpan';
    src: url('https://cdn.jsdelivr.net/gh/projectnoonnu/noonfonts_2302@1.0/KCC-Ganpan.woff2') format('woff2');
    font-weight: normal;
    font-style: normal;
}
* {
    font-family: 'KCC-Ganpan';
}

a {
    text-decoration-line: none;
    color: black;
    font-size: 20px;
}
</style>

{% endblock style %}

{% block content %}
<div class="container text-center m-5">
    <h1 class ='mb-3 col'>Todo List  
    <a style="color:pink;" href="{% url 'todos:create' %}">추가</a></h1>
{% for todo in  todos %}
  <div class = "border border-warning-subtle rounded-3 mb-3 p-4 w-50 mx-auto shadow text-start">
    <a href="{% url 'todos:todocontent' todo.pk %}"> 
    <h4>Todo : {{todo.title}} </h4>
    <h5>Explanation : {{todo.content}} </h5>

    <label for="completed">completed</label>
    <input type="checkbox" name="completed" id="completed" 
    style='zoom:1.5;' {% if todo.completed %}checked{% endif %} disabled>
    </a>
  </div>    
{% endfor %}
</div>
{% endblock content %}