study/DJANGO/task/APR05/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('join/', views.join, name='join'),
    path('withdraw/', views.withdraw, name='withdraw'),
    path('update/', views.update, name='update'),
    path('password/', views.change_password, name='change_password'),
    path('mypage/<int:pk>', views.mypage, name='mypage'),
] 

study/DJANGO/task/APR05/userpjt/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name='main'),
    path('accounts/',include('accounts.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/DJANGO/task/APR05/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
# Create your models here.

class User(AbstractUser):
    pass

study/DJANGO/task/APR05/accounts/forms.py
from django.contrib.auth.forms import UserChangeForm, UserCreationForm, AuthenticationForm, PasswordChangeForm
from django.contrib.auth import get_user_model
from django import forms

class CustomUserCreationForm(UserCreationForm):
    username = forms.CharField(
         label= '아이디',
         widget=forms.TextInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )
    error_messages = {
         'password_mismatch': ("비밀번호가 일치하지 않습니다."),
    }
    password1 = forms.CharField(
         label='비밀번호',
         widget=forms.PasswordInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )
    password2 = forms.CharField(
         label='비밀번호 확인',
         widget=forms.PasswordInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    ) 

    email = forms.CharField(
         label= '이메일',
         widget=forms.TextInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )
    first_name = forms.CharField(
         label= '이름',
         widget=forms.TextInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )
    class Meta(UserCreationForm.Meta):
        model = get_user_model()
    
    def clean_password2(self):
        password1 = self.cleaned_data.get("password1")
        password2 = self.cleaned_data.get("password2")
        if password1 and password2 and password1 != password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code = 'password_mismatch',
            )
        return password2
    def save(self, commit=True):
        user = super(UserCreationForm, self).save(commit=False)
        user.set_password(self.cleaned_data["password1"])
        if commit:
            user.save()
        return user
        

class CustomUserChangeForm(UserChangeForm):

    email = forms.CharField(
         label= '이메일',
         widget=forms.TextInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
        )
    )

    first_name = forms.CharField(
         label= '이름',
         widget=forms.TextInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )
    class Meta(UserChangeForm.Meta):
        model = get_user_model()
        fields = ('email', 'first_name')

class CustomAuthenticationForm(AuthenticationForm):
        username = forms.CharField(
            label='아이디',
            widget=forms.TextInput(
                attrs={
                    'placeholder' : '  ID',
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
        )
    )
        password = forms.CharField(
            label='비밀번호',
            widget=forms.PasswordInput(
                attrs={
                    'placeholder' : '  PASSWORD',
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
                }         
            )
        )

class CustomPasswordChangeForm(PasswordChangeForm):
    error_messages = {
         'password_mismatch': ("비밀번호가 일치하지 않습니다."),
    }

    old_password = forms.CharField(
         label='기존 비밀번호',
         widget=forms.PasswordInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )

    new_password1 = forms.CharField(
         label='새로운 비밀번호',
         widget=forms.PasswordInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )
    new_password2 = forms.CharField(
         label='비밀번호 확인',
         widget=forms.PasswordInput(
            attrs={
                    'style' : 'border: 2px firebrick solid; border-radius: 10px; font-size: 20px;'
            }
         )
    )

    # 기존 암호와 같을 경우
    def clean_new_password1(self):
        old_password = self.cleaned_data.get('old_password')
        new_password1 = self.cleaned_data.get('new_password1')

        if old_password and new_password1:
            if old_password == new_password1:
                raise forms.ValidationError('새로운 비밀번호는 기존 비밀번호와 다르게 입력해주세요')
        return new_password1
    
    # 새로운 암호가 서로 다를 경우
    def clean_new_password2(self):
        new_password1 = self.cleaned_data.get('new_password1')
        new_password2 = self.cleaned_data.get('new_password2')

        if new_password1 and new_password2 and new_password1 != new_password2:
            raise forms.ValidationError(
                self.error_messages['password_mismatch'],
                code = 'password_mismatch',
            )
        return new_password2
    

study/DJANGO/task/APR05/accounts/views.py
from django.shortcuts import render,redirect
from .models import User
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from .forms import CustomAuthenticationForm, CustomUserChangeForm, CustomUserCreationForm, CustomPasswordChangeForm
# Create your views here.

def login(request):
    if request.user.is_authenticated:
        return redirect('main')
    if request.method == 'POST':
        form = CustomAuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('main')      
    else:
        form = CustomAuthenticationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('main')

def join(request):
    if request.user.is_authenticated:
        return redirect('main')
       
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomUserCreationForm()
    context = {
        'form' : form,
    }
    return render(request, 'accounts/join.html', context)

def withdraw(request):
    request.user.delete()
    auth_logout(request)
    return redirect('main')

def update(request):
    if request.method == 'POST':
        form = CustomUserChangeForm(request.POST, instance=request.user)
        if form.is_valid():
            form.save()
            return redirect('main')
    else:
        form = CustomUserChangeForm(instance=request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/update.html',context)

def change_password(request):
    if request.method == 'POST':
        form = CustomPasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            form.save()
            return redirect('accounts:login')
    else:
        form = CustomPasswordChangeForm(request.user)
    context = {
        'form' : form,
    }
    return render(request, 'accounts/change_password.html', context)

def mypage(request, pk):
    user = User.objects.get(pk=pk)
    context ={
        'user' : user
    }
    return render(request, 'accounts/mypage.html', context)

study/DJANGO/task/APR05/accounts/templates/accounts/change_password.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock style %}

{% block content %}

<div class="box">
    <div class="title">
        <h1>비밀번호 변경</h1>
    </div>
    <div class="login_input">
        <form action="{% url 'accounts:change_password' %}" method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn_style" value= "Update">
            <a href="{% url 'accounts:update' %}" class="btn btn_style">Back</a>
        </form>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR05/accounts/templates/accounts/join.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock style %}

{% block content %}

<div class="box">
    <div class="title">
        <h1>회원가입</h1>
    </div>
    <div class="join_input">
        <form action="{% url 'accounts:join' %}" method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn_style" value= "Join">
            <a href="{% url 'main' %}" class="btn btn_style">Back</a>
        </form>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR05/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock style %}

{% block content %}

<div class="box">
    <div class="title">
        <h1>로그인</h1>
    </div>
    <div class="login_input">
        <form action="{% url 'accounts:login' %}" method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn_style" value= "Login">
            <a href="{% url 'accounts:join' %}" class="btn btn_style">Join</a>
            <a href="{% url 'main' %}" class="btn btn_style">Back</a>
        </form>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR05/accounts/templates/accounts/mypage.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock style %}

{% block content %}

<div class="box">
    <div class="title">
        <h1>마이페이지</h1>
    </div>
    <div class="login_input">
        <p>아이디 : {{ user.username }}</p>
        <p>이메일 : {{ user.email }}</p>
        <p>이름 : {{ user.first_name}}</p>
        <a href="{% url 'accounts:update' %}" class="btn btn_style">Update</a>
        <a href="{% url 'main' %}" class="btn btn_style">Back</a>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR05/accounts/templates/accounts/update.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/accounts.css' %}">
{% endblock style %}

{% block content %}

<div class="box">
    <div class="title">
        <h1>정보수정</h1>
    </div>
    <div class="update_input">
        <form action="{% url 'accounts:update' %}" method="POST" >
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" class="btn btn_style" value= "Save">
            <a href="{% url 'main' %}" class="btn btn_style">Back</a>
        </form>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR05/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    {% endblock style %}

</head>
<body>
    {% block content %}
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
    crossorigin="anonymous"></script>
</body>
</html>

study/DJANGO/task/APR05/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock style %}


{% block content %}

{% if request.user.is_authenticated %}

<div class='title'>
    <h1>안녕하세요, {{ user }} 님:)</h1>
</div>
<div class='mypage'>
    <a href="{% url 'accounts:mypage' user.pk %}">My Page</a>
</div>
<div class='btn_box'>
    <form action="{% url 'accounts:logout' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="로그아웃" class="btn btn_style">
    </form>
    <form action="{% url 'accounts:withdraw' %}" method="POST">
    {% csrf_token %}
    <input type="submit" value='회원탈퇴' class="btn btn_style" onclick="return confirm('탈퇴 시, 더 이상 서비스를 이용하실 수 없습니다.                            정말 탈퇴하시겠습니까?')">
    </form>
    <a href="{% url 'accounts:update' %}" class="btn btn_style">정보수정</a>
</div>
{% else %}
<div class='title'>
    <h1>안녕하세요, 방문자님!</h1>
    <h1>로그인을 해주세요:)</h1>
</div>

<div class='btn_box'>
    <a href="{% url 'accounts:login' %}" class="btn btn_style">로그인</a>
    <a href="{% url 'accounts:join' %}" class="btn btn_style">회원가입</a>
</div>
{% endif %}

{% endblock content %}