study/DJANGO/task/APR04/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'
urlpatterns = [
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),   
]

study/DJANGO/task/APR04/crud/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from . import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name = 'main'),
    path('accounts/', include('accounts.urls')),
    path('diaries/', include('diaries.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

study/DJANGO/task/APR04/diaries/urls.py
from django.urls import path
from . import views

app_name = 'diaries'
urlpatterns = [
    path('', views.diary, name='diary'),
    path('<int:pk>/', views.diarypage, name='diarypage'),
    path('write/', views.write, name='write'),
    path('<int:pk>/delete/', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name = 'edit'),
]

study/DJANGO/task/APR04/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

study/DJANGO/task/APR04/diaries/models.py
from django.db import models
import os
from django.conf import settings
# Create your models here.



class Diary(models.Model):
    title = models.CharField(max_length=50)
    record_date = models.DateTimeField(null=True, blank=True)
    imgfile = models.ImageField(null=True, upload_to="", blank=True)
    content = models.TextField()

    #게시글 삭제시 첨부한 파일 삭제
    def delete(self, *args, **kargs):
        if self.imgfile:
            os.remove(os.path.join(settings.MEDIA_ROOT, self.imgfile.path))
        super(Diary, self).delete(*args, **kargs)

study/DJANGO/task/APR04/diaries/forms.py
from django import forms
from .models import Diary

class DiaryForm(forms.ModelForm):
    title = forms.CharField(
        label='Title',
        widget=forms.TextInput(
            attrs={
                'placeholder' : '  제목',
                'style' : 'border: 2px rgb(201, 186, 244) solid; border-radius: 10px;'
            },
        )
    )

    record_date = forms.DateField(
        label='Date.',
    widget=forms.DateInput(
        attrs={
                'type': 'date',
                'style' : 'border: 2px rgb(201, 186, 244) solid; border-radius: 10px;'
        },
    )
)
    content = forms.CharField(
    label='Text',
    widget=forms.Textarea(
        attrs={
                'placeholder' : '  내용',
                'cols': '30', 'rows':'5',
                'style' : 'border: 2px rgb(201, 186, 244) solid; border-radius: 10px;'
        }, 
    )
)

    class Meta:
        model = Diary
        fields = '__all__'

study/DJANGO/task/APR04/accounts/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.forms import AuthenticationForm
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout

# Create your views here.

def login(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, request.POST)
        if form.is_valid():
            auth_login(request, form.get_user())
            return redirect('main')
    else:
        form = AuthenticationForm()
        form.fields['username'].label = "아이디"
        form.fields['username'].widget.attrs['style'] = "border: 1px rgb(201, 186, 244) solid; border-radius: 10px;"
        form.fields['username'].widget.attrs['placeholder'] = "   ID"
        form.fields['password'].widget.attrs['style'] = "border: 1px rgb(201, 186, 244) solid; border-radius: 10px;"
        form.fields['password'].widget.attrs['placeholder'] = "   Password"
    
    context = {
        'form' : form,
    }
    return render(request, 'accounts/login.html', context)

def logout(request):
    auth_logout(request)
    return redirect('main')

study/DJANGO/task/APR04/crud/views.py
from django.shortcuts import render,redirect


# Create your views here.

def main(request):
    return render (request, 'main.html')

study/DJANGO/task/APR04/diaries/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Diary
from .forms import DiaryForm

# Create your views here.

def diary(request, year=None, month=None):
    diaries = Diary.objects.order_by('record_date')
    year = request.GET.get('year')
    month = request.GET.get('month')

    if year and month:
        diaries = diaries.filter(record_date__year=year, record_date__month=month)

    context = {
        'diaries' : diaries,
        'years' : range(2020,2024),
        'months' : range(1,13),
    }
    return render(request, 'diaries/diary.html', context)  

def diarypage(request, pk):
    diary = Diary.objects.get(pk=pk)
    context = {
        'diary' : diary,
    }
    return render(request,'diaries/diarypage.html', context)


def write(request):
    if request.method == 'POST':
        form = DiaryForm(request.POST, request.FILES)
        if form.is_valid():
            diary = form.save()
            return redirect('diaries:diarypage', diary.pk)
    else:
        form = DiaryForm()
    context = {
        'form' : form,
    }
    return render(request, 'diaries/write.html', context)


def delete(request, pk):
    diary = Diary.objects.get(pk=pk)
    diary.delete()
    return redirect("diaries:diary")


def edit(request, pk):
    if request.method == 'POST':
        diary = Diary.objects.get(pk=pk)
        form = DiaryForm(request.POST, request.FILES, instance=diary)
        if form.is_valid():
            diary = form.save()
            return redirect('diaries:diarypage', diary.pk)
    else:
        diary = Diary.objects.get(pk=pk)
        form = DiaryForm(instance=diary)
    context = {
        'diary': diary,
        'form' : form,
    }
    return render(request, 'diaries/edit.html', context)

study/DJANGO/task/APR04/diaries/templates/diaries/diary.html
{% extends 'base.html' %}
{% load static %}


{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/diary.css' %}">
{% endblock style %}

{% block content %}
<div class="container">
    <div class="dairy_header">
    <h1>Diary</h1>
    <a class="btn btn_style" href="{% url 'diaries:write' %}">일기쓰기</a></h1>
    </div>
    <form action="{% url 'diaries:diary' %}" method="get" class="text-center">
        <label for="year">Year:</label>
        <select name="year" id="year">
            <option value="">Select year</option>
            {% for year in years %}
              {% if year == selected_year %}
                <option value="{{ year }}" selected>{{ year }}년</option>
              {% else %}
                <option value="{{ year }}">{{ year }}년</option>
              {% endif %}
            {% endfor %}
        </select>
        <label for="month">Month:</label>
        <select name="month" id="month">
            <option value="">Select month</option>
            {% for month in months %}
                <option value="{{ month }}"> {{ month }}월</option>
            {% endfor %}
        </select>
        <button type="submit" class="btn btn_style">Filter</button>
    </form>

    {% for diary in diaries %}
        <div class="dairy_content">
            <div class="dairy_content__txt">
                <a href="{% url 'diaries:diarypage' diary.pk %}">
                    <h4>{{ diary.record_date|date:'m/d' }}♥</h4>
                    <h4>{{ diary.title }}</h4>
                </a>
            </div>
        </div>
    {% empty %}
    <div class="dairy_content">
      <h4>♡기록이 없습니다♡<h4>
    </div>
    {% endfor %}
</div>

{% endblock content %}

study/DJANGO/task/APR04/diaries/templates/diaries/diarypage.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/diary.css' %}">
{% endblock style %}

{% block content %}
<div class="dairy_page">
  <h1> {{diary.record_date|date:'Y/m/d'}}의 기록</h1>
  <h3> {{diary.title}} </h3>

  {% if diary.imgfile %}
  <div class='img_box'>
    <div class="img_border">
        <img src="{{ diary.imgfile.url }}" alt="" class="img">
    </div>
  </div>
  {% endif %}
  <h4 class="dairy_page__content">{{diary.content}}</h4>

  <a href="{% url 'diaries:edit' diary.pk %}" class="btn btn_style">수정</a>
  <a href="{% url 'diaries:delete' diary.pk %}" class="btn btn_style" onclick="return confirm('정말 삭제하시겠습니까?')">삭제</a>
  <a href="{% url 'diaries:diary' %}" class="btn btn_style">뒤로가기</a>
</div>
{% endblock content %}

study/DJANGO/task/APR04/diaries/templates/diaries/edit.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/diary.css' %}">
{% endblock style %}


{% block content %}

<div class="write_box">
    <h1>Today record</h1>
    <div class="write_box__form">
        <form action="{% url 'diaries:edit' diary.pk %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="btn_box">
                <input class="btn btn_style" type="submit" id='submit-button' value="Save">
                <a href="{% url 'diaries:diarypage' diary.pk%}" class="btn btn_style">Back</a>
            </div>
        </form>
    </div>
</div>

{% endblock content %}

study/DJANGO/task/APR04/diaries/templates/diaries/write.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/diary.css' %}">
{% endblock style %}


{% block content %}

<div class="write_box">
    <h1>Today record</h1>
    <div class="write_box__form">
        <form action="{% url 'diaries:write' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.as_p }}
            <div class="btn_box">
                <input class="btn btn_style" type="submit" id='submit-button' value="Save">
                <a href="{% url 'diaries:diary' %}" class="btn btn_style">Back</a>
            </div>
        </form>
    </div>
</div>
{% endblock content %}

study/DJANGO/task/APR04/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    {% block style %}
    
    {% endblock style %}
</head>
<body>
    
    {% block content %}
    
    {% endblock content %}
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" 
    integrity="sha384-w76AqPfDkMBDXo30jS1Sgez6pr3x5MlQ1ZAGC+nuZB+EYdgRZgiwxhTBTkF7CXvN" 
    crossorigin="anonymous"></script>
</body>
</html>

study/DJANGO/task/APR04/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
{% endblock style %}


{% block content %}

<header class="center">
    <div class="main_title">
        <h1>{{ user }}님의 Menu</h1>
        <div class = "login_box">
            <a href="{% url 'accounts:login' %}" class = "btn btn_style ">Login</a>
            <form action="{% url 'accounts:logout' %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Logout" class = "btn btn_style ">
            </form>
        </div>
    </div>
</header>

<div class="container">
    <div class="center">
        <a href="/diaries/">Diary</a>
    </div>
</div>

{% endblock content %}